### ISSUE TITLE
PyQt have issue with parse?? ImportError: cannot import name 'parse' from 'sipbuild.code_generator'

### ISSUE THREAD

**Issue by kevinsmia1939** [flathub/com.riverbankcomputing.PyQt.BaseApp#28]
Hi,
I have issue with building Veusz using PyQt baseapp.

Here is my spec file.
https://github.com/kevinsmia1939/io.github.veusz.Veusz

```
Running: pip3 install --verbose --exists-action=i --no-index --find-links=file://${PWD} --prefix=${FLATPAK_DEST} .
Using pip 22.0.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
Looking in links: file:///run/build/Veusz
Processing /run/build/Veusz
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/run/build/Veusz/setup.py", line 35, in <module>
      import pyqtdistutils
    File "/run/build/Veusz/pyqtdistutils.py", line 15, in <module>
      from sipbuild.code_generator import set_globals, parse, generateCode
  ImportError: cannot import name 'parse' from 'sipbuild.code_generator' (/app/lib/python3.9/site-packages/sipbuild/code_generator.abi3.so)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```
I wonder could it be issue with building sip with parse?
Thanks.

**Comment by tinywrkb** [comment]
Maybe that's an upstream issue? Here are suggested changes, though it still doesn't build.

```
diff --git a/io.github.veusz.Veusz.yaml b/io.github.veusz.Veusz.yaml
index f0287a9..f96d0a7 100644
--- a/io.github.veusz.Veusz.yaml
+++ b/io.github.veusz.Veusz.yaml
@@ -257,6 +257,8 @@ modules:
         x-checker-data:
           type: git
           tag-pattern: ^(veusz-[\d.]+)$
+      - type: patch
+        path: veusz-pyqtdistutils-parse-import.patch
       #- type: patch
         #path: change-pyqt-dir.patch
       #- type: patch
diff --git a/veusz-pyqtdistutils-parse-import.patch b/veusz-pyqtdistutils-parse-import.patch
new file mode 100644
index 0000000..ef83832
--- /dev/null
+++ b/veusz-pyqtdistutils-parse-import.patch
@@ -0,0 +1,24 @@
+diff --git a/pyqtdistutils.py b/pyqtdistutils.py
+index 5156108a..5394ba90 100644
+--- a/pyqtdistutils.py
++++ b/pyqtdistutils.py
+@@ -12,8 +12,9 @@ import distutils.command.build_ext
+
+ import toml
+
+-from sipbuild.code_generator import set_globals, parse, generateCode
++from sipbuild.code_generator import set_globals, generateCode
+ from sipbuild.exceptions import UserException
++from sipbuild.generator import parse
+ from sipbuild.module import copy_sip_h, resolve_abi_version
+ from sipbuild.version import SIP_VERSION, SIP_VERSION_STR
+
+@@ -228,7 +229,7 @@ class build_ext(distutils.command.build_ext.build_ext):
+     def _sip_compile(self, source, sip_builddir):
+         """Compile sip file to sources."""
+         sip_module = 'PyQt5.sip'
+-        pyqt5_include_dir = os.path.join(get_python_lib(plat_specific=1),
++        pyqt5_include_dir = os.path.join(get_python_lib(plat_specific=1, prefix='/app'),
+                                          'PyQt5', 'bindings')
+         pyqt5_toml = os.path.join(pyqt5_include_dir, 'QtCore', 'QtCore.toml')
+         pyqt5_cfg = toml.load(pyqt5_toml)
```

**Comment by tinywrkb** [comment]
Actually, maybe the best solution is to use a pre-6.6.0 sip release until Veusz catch up.

```
diff --git a/io.github.veusz.Veusz.yaml b/io.github.veusz.Veusz.yaml
index f0287a9..4cc2926 100644
--- a/io.github.veusz.Veusz.yaml
+++ b/io.github.veusz.Veusz.yaml
@@ -231,6 +231,16 @@ modules:
         x-checker-data:
           type: pypi
           name: parse
+  - name: sip65
+    buildsystem: simple
+    build-commands:
+      - rm -f ${FLATPAK_DEST}/bin/sip-*
+      - python setup.py build
+      - python setup.py install --skip-build --prefix=$FLATPAK_DEST --root=/ --optimize=1
+    sources:
+      - type: archive
+        url: https://files.pythonhosted.org/packages/de/c1/9ac5596c10f6ce28abc1849ed1b6299b3953af0b6ff21e227024991a517e/sip-6.5.1.tar.gz
+        sha256: 204f0240db8999a749d638a987b351861843e69239b811ec3d1881412c3706a6
 
   - name: Veusz
     buildsystem: simple
@@ -257,6 +267,8 @@ modules:
         x-checker-data:
           type: git
           tag-pattern: ^(veusz-[\d.]+)$
+      - type: patch
+        path: veusz-pyqtdistutils-pyqt-includedir.patch
       #- type: patch
         #path: change-pyqt-dir.patch
       #- type: patch
diff --git a/veusz-pyqtdistutils-pyqt-includedir.patch b/veusz-pyqtdistutils-pyqt-includedir.patch
new file mode 100644
index 0000000..d48301e
--- /dev/null
+++ b/veusz-pyqtdistutils-pyqt-includedir.patch
@@ -0,0 +1,13 @@
+diff --git a/pyqtdistutils.py b/pyqtdistutils.py
+index 5156108a..78ea7a66 100644
+--- a/pyqtdistutils.py
++++ b/pyqtdistutils.py
+@@ -228,7 +228,7 @@ class build_ext(distutils.command.build_ext.build_ext):
+     def _sip_compile(self, source, sip_builddir):
+         """Compile sip file to sources."""
+         sip_module = 'PyQt5.sip'
+-        pyqt5_include_dir = os.path.join(get_python_lib(plat_specific=1),
++        pyqt5_include_dir = os.path.join(get_python_lib(plat_specific=1, prefix='/app'),
+                                          'PyQt5', 'bindings')
+         pyqt5_toml = os.path.join(pyqt5_include_dir, 'QtCore', 'QtCore.toml')
+         pyqt5_cfg = toml.load(pyqt5_toml)
```

**Comment by tinywrkb** [comment]
Anyway, closing as this is clearly not a base application issue.

**Comment by kevinsmia1939** [comment]
thank you so much
